export default {
  dialogDirection: 'rtl',
  dialogType: 'drawer',
  dialogModal: false,
  dialogEscape: false,
  highlightCurrentRow: true,
  border: true,
  stripe: true,
  index: true,
  indexLabel: '序号',
  page: true,
  align: 'center',
  menuAlign: 'left',
  menuWidth: '140',
  menuType: 'text',
  addBtn: true,
  size: 'mini',
  refreshBtn: false,
  column: []
};
