export default {
  dialogDirection: 'rtl',
  dialogType: 'drawer',
  dialogWidth: '30%',
  border: true,
  stripe: true,
  index: true,
  indexLabel: '序号',
  page: false,
  align: 'center',
  menuAlign: 'left',
  menuWidth: '140',
  addBtn: false,
  header: false,
  addBtnText: '新增行',
  simplePage: true,
  size: 'mini',
  refreshBtn: false,
  searchBtn: false,
  filterBtn: false,
  columnBtn: false,
  column: []
};
