{
  "material-cost":{
      "tableJson":[
          {
              "prop":"name",
              "display":"true"
          },
          {
              "prop":"spec",
              "display":"true"
          },
          {
              "prop":"unit",
              "display":"true"
          },
          {
              "prop":"net",
              "display":"false"
          },
          {
              "prop":"expendable-weight",
              "display":"false"
          },
          {
              "prop":"unitprice",
              "display":"false"
          },
          {
              "prop":"price",
              "display":"false"
          }
      ]
  },
  "outsocring":{
      "tableJson":[
          {
              "prop":"name",
              "display":"false"
          },
          {
              "prop":"spec",
              "display":"true"
          },
          {
              "prop":"unit",
              "display":"true"
          },
          {
              "prop":"number",
              "display":"true"
          },
          {
              "prop":"unitprice",
              "display":"false"
          },
          {
              "prop":"price",
              "display":"false"
          }
      ]
  },
  "machine-cost":{
      "tableJson":[
          {
              "prop":"name",
              "display":"true"
          },
          {
              "prop":"device-weight",
              "display":"true"
          },
          {
              "prop":"device-rate",
              "display":"true"
          },
          {
              "prop":"hour-rate",
              "display":"true"
          },
          {
              "prop":"staff",
              "display":"false"
          },
          {
              "prop":"hourperunit",
              "display":"false"
          },
          {
              "prop":"price",
              "display":"false"
          }
      ]
  },
  "package-cost":{
      "fieldJson":[
          {
              "prop":"type",
              "display":"false"
          },
          {
              "prop":"pcs",
              "display":"false"
          },
          {
              "prop":"out-size",
              "display":"false"
          },
          {
              "prop":"inbox",
              "display":"false"
          },
          {
              "prop":"outbox-cost",
              "display":"false"
          },
          {
              "prop":"inbox-cost",
              "display":"false"
          }
      ]
  },
  "freight":{
      "fieldJson":[
          {
              "prop":"distance",
              "display":"false"
          },
          {
              "prop":"truckload",
              "display":"false"
          },
          {
              "prop":"price",
              "display":"false"
          }
      ]
  }
}